config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'welcome#index'
  get 'welcome' => 'welcome#index'
  get 'examples' => 'content_type_objects#index'
  get 'search' => 'search#index'
  get 'objects' => 'content_type_objects#show', as: 'object_show'
  get 'errors/500' => 'errors#internal_server_error'
  get 'errors/404' => 'errors#not_found'
  get 'errors/401' => 'errors#not_authorized'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :begin_timer

  def index
    @page_title = "Search results"
    @search_data = SearchData.new(SolrSearch.new(search_params).data)

    if @search_data.solr_error?
      render template: @search_data.error_partial_path, locals: { status: @search_data.error_code, message: @search_data.error_message }
    else
      @objects = @search_data.object_data
      unless @objects.blank?
        # Type facet hierarchy
        @type_facets = @search_data.type_facets
        @expanded_types = @search_data.expanded_types
        @hierarchy_data = @search_data.hierarchy_data

        # Associated objects
        @associated_object_results = AssociatedObjectsForSearchResults.new(@objects).data
        @associated_object_data = @associated_object_results.dig(:object_data)

        # SES data
        query_ses = @objects.map { |o| o.content_type_object_data.select { |k| o.class.search_result_ses_fields.include?(k) }.values }
        ses_ids = [@search_data.facet_ses_ids + @associated_object_results.dig(:ses_ids) + query_ses].flatten.uniq
        @ses_data = SesData.new(ses_ids, @search_data.hierarchy_ses_data).combined_ses_data
      end
    end
  end

  private

  def begin_timer
    @start_time = Time.now
  end

  def search_params
    params.permit(:commit, :query, :page, :results_per_page, :sort_by,
                  :show_detailed, :expanded_types, filter: {})
  end

  def permitted_filters
    # Not currently used

    hash = {}
    SolrSearch.facet_fields.each do |field|
      hash[field.to_sym] = []
    end

    hash
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_applied_filters.html.erb
<% unless request.params.dig(:filter).blank? %>
  <div class="applied-filters">
    <div class="applied-filter-container">
      <% request.params.dig(:filter).sort.uniq.each do |filter| %>
        <% filter.last.sort.each do |filter_value| %>
          <div class="filter-wrapper">
            <div class="filter">
              <div class="top-row">
                        <span class="filter-name-label">
                          <%= filter_field_name(filter.first) %>
                        </span>
                <span class="flex-spacer"></span>
                <span class="filter-link">
                  <%= link_to sanitize("&#x2717;"), url_for(remove_filter_url(request.params, filter.first, filter_value)), class: 'modifiable-link' %>
                </span>
              </div>
              <div class="bottom-row">
                <div class="filter-name">
                  <%= object_display_name({ value: filter_field_value(filter, filter_value), field_name: filter.first }, singular: false) %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/search/_control_panel_current.haml
%span.search-control-panel-current=value

app/views/search/_control_panel_link.haml
%span.search-control-panel-link=link_to(link_text, link_url, class: 'modifiable-link')

app/views/search/_filter_section.html.erb
<section class="facet">
  <h4 class="facet-heading <%= 'inactive' if facet_field[:facets].size == 0 %>"><%= filter_field_name(facet_field[:field_name]) %></h4>
  <div>
    <div>
    </div>
    <% facet_field[:facets][0..4].each do |facet| %>
      <div>
        <%= link_to_if(!request.params.dig(:filter, facet_field[:field_name])&.include?(facet["val"].to_s), "#{object_display_name({ value: facet["val"], field_name: facet_field[:field_name] }, singular: false, reading_order: false)} (#{number_to_delimited(facet["count"], separator: ",")})", url_for(apply_filter_url(request.params, facet_field[:field_name], facet["val"])), class: "menu-link modifiable-link", title: scope_note("#{facet["val"]}_scope_note")) %>
      </div>
    <% end %>
    <% unless facet_field[:facets][5..].blank? %>
      <details>
        <summary>More</summary>
        <% facet_field[:facets][5...].each do |facet| %>
          <div>
            <%= link_to_if(!request.params.dig(:filter, facet_field[:field_name])&.include?(facet["val"].to_s), "#{object_display_name({ value: facet["val"], field_name: facet_field[:field_name] }, singular: false, reading_order: false)} (#{number_to_delimited(facet["count"], separator: ",")})", url_for(apply_filter_url(request.params, facet_field[:field_name], facet["val"])), class: "menu-link modifiable-link", title: scope_note("#{facet[:val]}_scope_note")) %>
          </div>
        <% end %>
      </details>
    <% end %>
  </div>
</section>

app/views/search/_hierarchy_layer.html.erb
<% if id && @type_facets[id] %>
  <span class="grid-row">
    <span class="facet-toggle toggle-<%= parent_id %> <%= collapse(tier, @expanded_types, parent_id) %>" style="margin-left: <%= (tier - 1) * 0 %>px;">
      <% if has_children?(@hierarchy_data, id, @type_facets) %>
        <a class="hierarchy-toggle" data-expand-types-id-param="<%= id %>" data-action="click->expand-types#toggle">
          <%= raw toggle_symbol(@expanded_types, id) %>
        </a>
      <% else %>
      <div>
          -
      </div>
      <% end %>
    </span>

    <span class="facet-link toggle-<%= parent_id %> <%= collapse(tier, @expanded_types, parent_id) %>">
      <%= link_to_if(filter_applicable?(request.params, id), name_and_count(@hierarchy_data, id, @type_facets), url_for(apply_filter_url(request.params, 'type_sesrollup', id)), class: 'modifiable-link', title: scope_note("#{id}_scope_note")) %>
      <% if @hierarchy_data.dig(id) %>
        <% @hierarchy_data.dig(id, :children).each do |child| %>
          <%= render 'hierarchy_layer', id: child.dig(:id), tier: tier + 1, parent_id: id %>
        <% end %>
      <% end %>
    </span>
  </span>
<% end %>

app/views/search/_pagination.html.erb
<span id="pagination">
  <% if user_requested_page > 3 %>
    <span>
      <%= link_to "1", search_url(query: query, filter: filter, sort_by: sort_by, results_per_page: results_per_page, page: 1, expanded_types: expanded_types, show_detailed: show_detailed), class: 'modifiable-link' %>
    </span>
    <% if user_requested_page > 4 %>
      <span>
        ...
      </span>
    <% end %>
  <% end %>
  <% if user_requested_page > 2 %>
    <span>
      <%= link_to user_requested_page - 2, search_url(query: query, filter: filter, sort_by: sort_by, results_per_page: results_per_page, page: user_requested_page - 2, expanded_types: expanded_types, show_detailed: show_detailed), class: 'modifiable-link' %>
    </span>
  <% end %>
  <% if user_requested_page > 1 %>
    <span>
      <%= link_to user_requested_page -1, search_url(query: query, filter: filter, sort_by: sort_by, results_per_page: results_per_page, page: user_requested_page -1, expanded_types: expanded_types, show_detailed: show_detailed), class: 'modifiable-link' %>
    </span>
  <% end %>

  <span>
    <%= link_to user_requested_page, search_url(query: query, filter: filter, sort_by: sort_by, results_per_page: results_per_page, page: user_requested_page, expanded_types: expanded_types, show_detailed: show_detailed), class: 'selected modifiable-link' %>
  </span>

  <% if user_requested_page < last_page %>
    <span>
      <%= link_to user_requested_page + 1, search_url(query: query, filter: filter, sort_by: sort_by, results_per_page: results_per_page, page: user_requested_page + 1, expanded_types: expanded_types, show_detailed: show_detailed), class: 'modifiable-link' %>
    </span>
  <% end %>
  <% if user_requested_page < last_page - 1 %>
    <span>
      <%= link_to user_requested_page + 2, search_url(query: query, filter: filter, sort_by: sort_by, results_per_page: results_per_page, page: user_requested_page + 2, expanded_types: expanded_types, show_detailed: show_detailed), class: 'modifiable-link' %>
    </span>
  <% end %>
  <% if user_requested_page < last_page - 2 %>
    <% if user_requested_page < last_page - 3 %>
      <span>
        ...
      </span>
    <% end %>
    <span>
      <%= link_to last_page, search_url(query: query, filter: filter, sort_by: sort_by, results_per_page: results_per_page, page: last_page, expanded_types: expanded_types, show_detailed: show_detailed), class: 'modifiable-link' %>
    </span>
  <% end %>
</span>

app/views/search/_search_control_panel.html.erb
<div class="search-control-panel">
  <div class="search-control-panel-row">
    <%= render 'showing_results', include_time: false %>
  </div>
  <div class="search-control-panel-row">
            <span class="search-control-panel-item">
              <span class="search-control-panel-label">Show detailed:</span>
              <% if @search_data.show_detailed? %>
                <%= render 'control_panel_current', value: 'On' %>
                <%= render 'control_panel_link', link_text: 'Off', link_url: search_url(query: @search_data.query, filter: @search_data.filter, sort_by: @search_data.sort, results_per_page: @search_data.results_per_page, page: @search_data.current_page, expanded_types: @search_data.expanded_types_string, show_detailed: false) %>
              <% else %>
                <%= render 'control_panel_link', link_text: 'On', link_url: search_url(query: @search_data.query, filter: @search_data.filter, sort_by: @search_data.sort, results_per_page: @search_data.results_per_page, page: @search_data.current_page, expanded_types: @search_data.expanded_types_string, show_detailed: true) %>
                <%= render 'control_panel_current', value: 'Off' %>
              <% end %>
            </span>

    <span class="search-control-panel-item">
              <label class="search-control-panel-label">
                <span>Results:</span>
              </label>
      <% [10, 20, 50, 100].each do |per_page_option| %>
        <% if @search_data.results_per_page == per_page_option %>
          <%= render 'control_panel_current', value: per_page_option.to_i %>
        <% else %>
          <%= render 'control_panel_link', link_text: per_page_option.to_s, link_url: search_url(query: @search_data.query, filter: @search_data.filter, sort_by: @search_data.sort, results_per_page: per_page_option, page: 1, expanded_types: @search_data.expanded_types_string, show_detailed: @search_data.show_detailed) %>
        <% end %>
      <% end %>
    </span>

    <span class="search-control-panel-item">
              <label class="search-control-panel-label">
                <span>Sort by:</span>
              </label>
      <% if @search_data.sort == "date_desc" %>
        <%= render 'control_panel_current', value: 'Newest first' %>
        <%= render 'control_panel_link', link_text: 'Oldest first', link_url: search_url(query: @search_data.query, filter: @search_data.filter, sort_by: 'date_asc', results_per_page: @search_data.results_per_page, page: 1, expanded_types: @search_data.expanded_types_string, show_detailed: @search_data.show_detailed) %>
      <% else %>
        <%= render 'control_panel_link', link_text: 'Newest first', link_url: search_url(query: @search_data.query, filter: @search_data.filter, sort_by: 'date_desc', results_per_page: @search_data.results_per_page, page: 1, expanded_types: @search_data.expanded_types_string, show_detailed: @search_data.show_detailed) %>
        <%= render 'control_panel_current', value: 'Oldest first' %>
      <% end %>
    </span>
  </div>
</div>

app/views/search/_showing_results.html.erb
<span>
  <strong><%= @search_data.start %>-<%= [@search_data.end, @search_data.number_of_results].min %></strong>
    of
  <strong><%= number_to_delimited(@search_data.number_of_results, separator: ",") %></strong>
  results
  <% if include_time %>
    <span>(<%= "#{(Time.now - @start_time).round(2)} seconds" %>)</span>
  <% end %>
</span>

app/views/search/form.html.erb
<%= content_tag('p', @form.title) %>
<%= content_tag('p', @form.description) %>

<!--<section class="content-section">-->
<!--  <h3 class="content-heading">Example search results</h3>-->
<!--  <ul>-->
    <%#= content_tag('li', link_to('Research briefings', results_url(:document_type => 'research-briefings'))) %>
    <%#= content_tag('li', link_to('Written questions', results_url(:document_type => 'written-questions'))) %>
    <%#= content_tag('li', link_to('Written statements', results_url(:document_type => 'written-statements'))) %>
<!--  </ul>-->
<!--</section>-->

<!--<br/>-->

<section class="content-section">
  <h3 class="content-heading">Example Objects</h3>
  <ul>
    <%= content_tag('li', link_to('An EDM', object_show_url(object: 'http://data.parliament.uk/edms/22468'))) %>
    <%= content_tag('li', link_to('A research briefing', object_show_url(:object => 'http://data.parliament.uk/resources/342599'))) %>
    <%= content_tag('li', link_to('A written question', object_show_url(:object => 'http://hansard.intranet.data.parliament.uk/Lords/2012-12-10/1212106000156'))) %>
    <%= content_tag('li', link_to('A written statement', object_show_url(:object => 'http://hansard.intranet.data.parliament.uk/Commons/2012-12-18/12121863000016'))) %>
  </ul>
</section>

app/views/search/index.html.erb
<meta name="robots" content="noindex">

<% content_for(:before_title) do %>
  <%= link_to('UK Parliament', root_path) %> / <%= link_to('Open data', root_path) %><br/>
  <div id="top"></div>
<% end %>

<% if Rails.env.development? %>
  <%#= render 'content_type_objects/fragments/data', data: @objects, title: 'Secondary search objects' %>
  <%#= render 'content_type_objects/fragments/data', data: @associated_object_data, title: 'Associated object data' %>
  <%#= render 'content_type_objects/fragments/data', data: @search_data.search, title: 'Search response' %>
  <%#= render 'content_type_objects/fragments/data', data: @ses_data, title: 'SES results' %>
  <%#= render 'content_type_objects/fragments/data', data: @search_data.facets, title: 'Facets' %>
  <%#= render 'content_type_objects/fragments/data', data: @search_data.primary_member_facets, title: 'Primary Member Facets' %>
  <%#= render 'content_type_objects/fragments/data', data: @search_data.type_facets, title: 'Type facets' %>
  <%#= render 'content_type_objects/fragments/data', data: @search_data.hierarchy_data, title: 'Hierarchy data' %>
  <%#= render 'content_type_objects/fragments/data', data: @top_level, title: 'Hierarchy top level types' %>
  <%#= render 'content_type_objects/fragments/data', data: request.params, title: 'All params' %>
<% end %>

<%= form_with url: search_url, method: :get, remote: true, id: 'search-form' do |f| %>
  <div id="search" class="content-section white-slim">
    <div class="search-grid-container">
      <%= f.text_field :query, id: 'search-input', spellcheck: true, value: @search_data.query %>
      <%= f.hidden_field :show_detailed, value: @search_data.show_detailed %>
      <%= f.hidden_field :sort_by, value: @search_data.sort %>
      <%= f.hidden_field :results_per_page, value: @search_data.results_per_page %>
      <button id="search-button-large">
        New search
      </button>
      <button id="search-button-small">
        New search
      </button>
    </div>
  </div>
<% end %>

<% if @objects.blank? %>
  <div class="content-section white centered">
    <p>
      No results found for <strong><%= @search_data.query %></strong>. Please adjust your search query and try
      again.<br/>
      If you think this search should return results, please
      email <%= mail_to "parliamentarysearch@parliament.co.uk" %>.
    </p>
  </div>
<% else %>
  <div id="search-results">
    <div class="results-grid-container">
      <div class="filter-container" data-controller="expand-facet">
        <%= render 'applied_filters' %>
        <div id="facet-container-large">
          <%= render 'search/results/facets/type_facet' %>
          <% @search_data.facets.select { |h| ["legislature_ses", "session_t"].include?(h.dig(:field_name)) }.each do |facet_field| %>
            <%= render 'filter_section', facet_field: format_facets(facet_field) %>
          <% end %>
          <% @search_data.facets.select { |h| ["date_year", "date_month", "department_ses", "member_ses", "primaryMember_ses", "answeringMember_ses", "legislativeStage_ses", "legislationTitle_ses", "subject_ses", "publisher_ses"].include?(h.dig(:field_name)) }.each do |facet_field| %>
            <%= render 'filter_section', facet_field: format_facets(facet_field) %>
          <% end %>
        </div>
        <details id="facet-container-small">
          <summary>
            Filter results
          </summary>
          <%= render 'search/results/facets/type_facet' %>
          <% @search_data.facets.select { |h| ["legislature_ses", "session_t"].include?(h.dig(:field_name)) }.each do |facet_field| %>
            <%= render 'filter_section', facet_field: format_facets(facet_field) %>
          <% end %>
          <% @search_data.facets.select { |h| ["date_year", "date_month", "department_ses", "member_ses", "primaryMember_ses", "answeringMember_ses", "legislativeStage_ses", "legislationTitle_ses", "subject_ses", "publisher_ses"].include?(h.dig(:field_name)) }.each do |facet_field| %>
            <%= render 'filter_section', facet_field: format_facets(facet_field) %>
          <% end %>
        </details>
      </div>

      <div class="results-container">
        <%= render 'search_control_panel' %>

        <div data-controller="claw" data-action="keydown@document->claw#handleKeyDown">
          <% @objects.each do |object| %>
            <div class="search-result-container">
              <%= render object.search_result_partial, object: object unless object.class == NotSupported %>
              <%= render 'content_type_objects/fragments/search_claw', object: object %>
            </div>
          <% end %>
          <%= render '/content_type_objects/fragments/about_these_results' %>

          <% unless @search_data.current_page.blank? || @search_data.total_pages.blank? %>

            <p>
              <%= render 'showing_results', include_time: true %>
            </p>

            <% if @search_data.total_pages > 1 %>
              <%= render 'pagination', user_requested_page: @search_data.current_page, last_page: @search_data.total_pages, query: @search_data.query, filter: @search_data.filter, sort_by: @search_data.sort, results_per_page: @search_data.results_per_page, expanded_types: @search_data.expanded_types_string, show_detailed: @search_data.show_detailed %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

  </div>
<% end %>

app/views/search/results.html.erb
<div id="query-meta">
	<%= content_tag( 'p', "Query: #{results['responseHeader']['params']['q']}" ) %>
	<%= content_tag( 'p', "#{results['response']['numFound']} results found in #{results['responseHeader']['QTime']}ms." ) %>
	<%= content_tag( 'p', "Results offset: #{results['response']['start']}" ) %>
	<%= content_tag( 'p', "Status (of SOLR?): #{results['responseHeader']['status']}" ) %>
</div>

<div id="results">
	<%= content_tag( 'h2', 'Results' ) %>
	<% if results['response']['docs'].empty? -%>
		<%= content_tag( 'p', 'No results found for your search.' ) %>
	<% else -%>
		<ol>
			<%= render :partial => 'result', :collection => results['response']['docs'] %>
		</ol>
	<% end -%>
</div>

app/views/search/search_results_xml.html.erb
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0">

  <channel>
    <title>W3Schools Home Page</title>
    <link>https://www.w3schools.com</link>
    <description>Free web building tutorials</description>
    <item>
      <title>RSS Tutorial</title>
      <link>https://www.w3schools.com/xml/xml_rss.asp</link>
      <description>New RSS tutorial on W3Schools</description>
    </item>
  </channel>

</rss>

app/views/search/search_results_xml.rss.erb
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0">

  <channel>
    <title>W3Schools Home Page</title>
    <link>https://www.w3schools.com</link>
    <description>Free web building tutorials</description>
    <item>
      <title>RSS Tutorial</title>
      <link>https://www.w3schools.com/xml/xml_rss.asp</link>
      <description>New RSS tutorial on W3Schools</description>
    </item>
  </channel>

</rss>

app/views/search/search_results_xml.xml.erb
<?xml version="1.0" encoding="UTF-8" ?>
  <search_results>
  </search_results>